language: java
dist: trusty

cache:
  directories:
    - $HOME/.m2

# The latest java8
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8
  - openjdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:prepare-agent-integration verify
