language: java
dist: trusty

addons:
  apt:
    packages:
      - oracle-java8-installer

  sonarcloud:
    organization: exasol

jdk:
  - oraclejdk8
  - openjdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:prepare-agent-integration verify sonar:sonar -Dsonar.login=${SONAR_TOKEN}

cache:
  directories:
    - "$HOME/.m2"
