sudo: false
install: true

addons:
  sonarcloud:
    organization: exasol

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:prepare-agent-integration verify sonar:sonar -Dsonar.login=${SONAR_TOKEN}

cache:
  directories:
    - "$HOME/.m2"
    - '$HOME/.sonar/cache'
