version: '3'

services:

  # Exasol DB
  exasol-db:
    build:
      context: ./exasol-db-image
    image: custom/exasol-db
    container_name: exasol-db
    privileged: true
    ports:
      - 8888:8888
    volumes:
      - ./data/exa:/exa
      - ./data/test:/test

  # Kafka Stack
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.1
    container_name: zookeeper
    ports:
      - 2181:2181
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      default:
        aliases:
          - zookeeper.internal

  kafka01.internal:
    image: confluentinc/cp-kafka:4.1.1
    container_name: kafka01
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.internal:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka01.internal:9092

  kafka02.internal:
    image: confluentinc/cp-kafka:4.1.1
    container_name: kafka02
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.internal:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka02.internal:9093

  kafka03.internal:
    image: confluentinc/cp-kafka:4.1.1
    container_name: kafka03
    depends_on:
      - zookeeper
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.internal:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka03.internal:9094

  schema-registry:
    image: confluentinc/cp-schema-registry:4.1.1
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka01.internal
      - kafka02.internal
      - kafka03.internal
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper.internal:2181

  kafka-connect:
    #image: confluentinc/cp-kafka-connect:4.1.1
    build:
      context: ./kafka-connect-image
    image: custom/kafka-connect
    container_name: kafka-connect
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka01.internal:9092,kafka02.internal:9093,kafka03.internal:9094
      CONNECT_REST_ADVERTISED_PORT: 8083
      CONNECT_BOOTSTRAP_SERVERS: kafka01.internal:9092,kafka02.internal:9093,kafka03.internal:9094
      CONNECT_GROUP_ID: connect
      CONNECT_CONFIG_STORAGE_TOPIC: connect-config
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offset
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMA_IGNORE: "true"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LOG4J_LOGGERS: org.reflections=ERROR
      #CONNECT_LOG4J_ROOT_LOGLEVEL: DEBUG
      CONNECT_PLUGIN_PATH: "/usr/share/java/,/opt/kafka-connect/jars"
    depends_on:
      - kafka01.internal
      - schema-registry
      - exasol-db

  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    ports:
      - 9000:9000
    hostname: kafka-manager.internal
    environment:
      ZK_HOSTS: zookeeper.internal:2181
      APPLICATION_SECRET: littlepig-letmein
      KM_VERSION: 1.3.3.17
    depends_on:
      - zookeeper
      - kafka01.internal

  kafka-connect-ui:
    image: landoop/kafka-connect-ui:0.9.5
    container_name: kafka-connect-ui
    hostname: kafka-connect-ui
    ports:
      - 8003:8000
    environment:
      CONNECT_URL: "http://kafka-connect:8083/"
      PROXY: "true"
    depends_on:
      - kafka-connect
